---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Writing your lab"
      solveButton: true
    - name: module-02
      label: "Antora"
      solveButton: true
    - name: module-03
      label: "Tabs"

tabs:
  - name: ">_ control"
    url: /wetty
  - name: control
    url: https://control-${guid}.${domain}/
  - name: gitea
    url: https://gitea-${guid}.${domain}/
    external: true
  - name: node3
    url: http://node03-${guid}.${domain}/
  - name: node02
    url: http://node02-${guid}.${domain}/oscap-reports/ospp/
