---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Backup and Snapshots"
      solveButton: false
    - name: module-02
      label: "Infrastructure Reporting"
      solveButton: false
    - name: module-03
      label: "Windows Reporting"
      solveButton: false

tabs:
  - name: control
    url: https://control-${guid}.${domain}/
  # - name: gitea
  #   url: https://gitea-${guid}.${domain}/
    external: false
  - name: Report Server
    url: http://node03-${guid}.${domain}/
    external: false
  - name: Windows Reports
    url: http://node02-${guid}.${domain}/oscap-reports/ospp/
    external: false
  - name: ">_ control"
    url: /wetty
