---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Backup and Snapshots"
      solveButton: false
    - name: module-02
      label: "Infrastructure Reporting"
      solveButton: false
    - name: module-03
      label: "Windows Reporting"
      solveButton: false

tabs:
  - name: control
    url: https://control-${guid}.${domain}/
  # - name: gitea
  #   url: https://gitea-${guid}.${domain}/
    external: false
  - name: Report Server
    url: https://node03-${guid}.${domain}/index.html
    external: false
  - name: OpenScap Report
    url: https://node02-${guid}.${domain}/oscap-reports/ospp/
    external: false
  - name: Windows
    url: https://windows-ironrdp-${guid}.${domain}/
    external: false
  - name: ">_ control"
    url: /wetty
  - name: Cloud (PoC)
    url: /cloud
