---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Incident creation"
      solveButton: false
    - name: module-02
      label: "Attaching a problem"
      solveButton: false
    - name: module-03
      label: "Root cause, fix and close"
      solveButton: false
    - name: module-04
      label: "Query and update ServiceNow"
      solveButton: false
    - name: module-05
      label: "Query and update records"
      solveButton: false
    - name: module-06
      label: "Use ServiceNow as an inventory"
      solveButton: false

tabs:
  - name: AAP
    url: https://control-${guid}.${domain}/
    external: false
  - name: "VS Code"
    url: https://code-server-${guid}.${domain}/
    external: false
  - name: ServiceNow
    url: https://ansible.service-now.com
    external: true
